# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 18:31
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=3857)),
                ('properties', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text=b'The name of the layer as it will appear in URLs e.g http://domain.com/blog/my-slug/ and expressions e.g map(my-slug)', max_length=250, unique=True)),
                ('bounds', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), null=True, size=4)),
                ('field_names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, b'Good'), (1, b'Working'), (3, b'Bad')], default=1)),
            ],
        ),
        migrations.AddField(
            model_name='feature',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Layer'),
        ),
    ]
