# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 21:41
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='properties',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
