# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0002_layer_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('layer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='layers.Layer')),
            ],
        ),
    ]
