# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_layerfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerfile',
            name='status',
            field=models.CharField(blank=True, choices=[(b'working', b'Working'), (b'finished', b'Finished'), (b'failed', b'Failed')], max_length=10, null=True),
        ),
    ]
