# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_layerfile_status2'),
    ]

    operations = [
        migrations.AddField(
            model_name='layerfile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layerfile',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
