# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_geokitsite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geokitsite',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
