# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 19:18
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=75)),
                ('description', models.TextField(blank=True, null=True)),
                ('temporal_domain', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None)),
                ('spatial_domain', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('tree', django.contrib.postgres.fields.jsonb.JSONField()),
                ('input_variables', django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True)),
                ('units', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
