# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'variables', '0002_variable_status'), (b'variables', '0003_remove_variable_status'), (b'variables', '0004_variable_status')]

    dependencies = [
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='status',
            field=models.IntegerField(choices=[(0, 'Good'), (1, 'Working'), (3, 'Bad')], default=0),
            preserve_default=False,
        ),
    ]
