# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datasource',
            name='source_type',
        ),
    ]
