# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0002_variable_status_squashed_0004_variable_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='status',
            field=models.IntegerField(choices=[(0, 'Good'), (1, 'Working'), (3, 'Bad')], default=1),
        ),
    ]
