# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 20:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0002_remove_datasource_source_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='data_source',
        ),
        migrations.AddField(
            model_name='variable',
            name='tree',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
