# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0003_auto_20160630_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expressiondatasource',
            name='datasource_ptr',
        ),
        migrations.RemoveField(
            model_name='expressiondatasource',
            name='expression',
        ),
        migrations.RemoveField(
            model_name='uploadsdatasource',
            name='datasource_ptr',
        ),
        migrations.RemoveField(
            model_name='uploadsdatasource',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='uploadsdatasource',
            name='table',
        ),
        migrations.RemoveField(
            model_name='variabledatasource',
            name='datasource_ptr',
        ),
        migrations.RemoveField(
            model_name='variabledatasource',
            name='parent_variable',
        ),
        migrations.DeleteModel(
            name='DataSource',
        ),
        migrations.DeleteModel(
            name='ExpressionDataSource',
        ),
        migrations.DeleteModel(
            name='UploadsDataSource',
        ),
        migrations.DeleteModel(
            name='VariableDataSource',
        ),
    ]
