# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0003_auto_20170201_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='saved_dimensions',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
