# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_layerfile'),
        ('variables', '0004_variable_saved_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raster_id', models.CharField(max_length=512)),
                ('dates', models.CharField(max_length=512)),
                ('job_id', models.CharField(max_length=512)),
                ('status', models.IntegerField(choices=[(0, 'Good'), (1, 'Working'), (3, 'Bad')], default=1)),
                ('vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layers.Layer')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rasterrequest',
            unique_together=set([('raster_id', 'dates', 'vector')]),
        ),
    ]
