# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0004_variable_saved_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
