# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0005_auto_20160801_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variable',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
