# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0006_auto_20170308_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variable',
            name='spatial_domain'
        ),
        migrations.AddField(
            model_name='variable',
            name='spatial_domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='layers.Layer'),
        ),
    ]
