# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0008_auto_20160901_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
