# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 21:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0011_variable_input_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='input_variables',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[], null=True),
        ),
    ]
