# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('variables', '0012_auto_20161025_2128'),
        ('variables', '0011_result'),
    ]

    operations = [
    ]
