# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='aggregate_dimension',
            field=models.CharField(blank=True, choices=[(b'SP', b'Across space'), (b'TM', b'Across time'), (b'NA', b'Do not aggregate')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='expression',
            name='aggregate_method',
            field=models.CharField(choices=[(b'MEA', b'Mean'), (b'MED', b'Median'), (b'MOD', b'Mode'), (b'RAN', b'Range'), (b'STD', b'Std dev')], default=b'NA', max_length=2),
        ),
        migrations.AddField(
            model_name='expression',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
