# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0003_auto_20160219_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='aggregate_method',
            field=models.CharField(blank=True, choices=[(b'MEA', b'Mean'), (b'MED', b'Median'), (b'MOD', b'Mode'), (b'RAN', b'Range'), (b'STD', b'Std dev')], max_length=3, null=True),
        ),
    ]
