# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0004_auto_20160219_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
