# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0005_auto_20160222_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='units',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
