# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expressions', '0008_auto_20160518_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expression',
            name='spatial_domain_features',
        ),
        migrations.RemoveField(
            model_name='expression',
            name='temporal_domain',
        ),
    ]
