# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 19:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geokit_tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='date',
        ),
        migrations.AddField(
            model_name='record',
            name='date_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(null=True),
        ),
    ]
