# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-30 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geokit_tables', '0003_geokittable_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='geokittable',
            name='status',
            field=models.IntegerField(choices=[(0, 'Good'), (1, 'Working'), (3, 'Bad')], default=1),
        ),
    ]
