# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geokit_tables', '0004_geokittable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoKitTableFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geokit_tables.GeoKitTable')),
            ],
        ),
    ]
