# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 20:30
from __future__ import unicode_literals

import builder.blocks
from django.db import migrations
import variables.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('graph', wagtail.wagtailcore.blocks.StructBlock([(b'variable', variables.blocks.VariableChooserBlock())])), ('map', wagtail.wagtailcore.blocks.StructBlock([(b'variable', variables.blocks.VariableChooserBlock()), (b'color_ramp', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'value', wagtail.wagtailcore.blocks.CharBlock()), (b'color', builder.blocks.ColorBlock())])))])), ('table', wagtail.wagtailcore.blocks.StructBlock([(b'variable', variables.blocks.VariableChooserBlock())]))]),
        ),
    ]
