# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import layers.blocks
import variables.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20160608_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField([('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('graph', wagtail.wagtailcore.blocks.StructBlock([(b'variable', variables.blocks.VariableChooserBlock())])), ('map', wagtail.wagtailcore.blocks.StructBlock([(b'layer', layers.blocks.LayerChooserBlock()), (b'variable', variables.blocks.VariableChooserBlock()), (b'color_ramp', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock([(b'min_value', wagtail.wagtailcore.blocks.CharBlock()), (b'max_value', wagtail.wagtailcore.blocks.CharBlock()), (b'color', wagtail.wagtailcore.blocks.CharBlock())])))])), ('table', wagtail.wagtailcore.blocks.StructBlock([(b'variables', wagtail.wagtailcore.blocks.ListBlock(variables.blocks.VariableChooserBlock()))]))]),
        ),
        migrations.AlterField(
            model_name='formvariablefield',
            name='choices',
            field=models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices'),
        ),
    ]
